config/routes.rb
Rails.application.routes.draw do
  resources :todos
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'todos#index'
get 'todos/download_verbatim'
get '/todos/new(.:format)' , to: 'todos#copy' , as: 'copy_todo'
get '/todos/:id/error', to: 'todos#error' , as: 'error_todo'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    mount_uploader :Mapping_file, MappingUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
  protect_from_forgery with: :exception
  
  include Error::ErrorHandler
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/copy.html.erb
<script type="text/javascript">
$(document).ready(function(){    
    //Check if the current URL contains '#'
    if(document.URL.indexOf("#")==-1){
        // Set the URL to whatever it was plus "#".
        url = document.URL+"#";
        location = "#";

        //Reload the page
        location.reload(true);
    }
});
</script>


<h1>Copy New Project</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/edit.html.erb
<script type="text/javascript">
$(document).ready(function(){    
    //Check if the current URL contains '#'
    if(document.URL.indexOf("#")==-1){
        // Set the URL to whatever it was plus "#".
        url = document.URL+"#";
        location = "#";

        //Reload the page
        location.reload(true);
    }
});
</script>


<h1>Editing Project</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/error.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Error:</strong>
  
  
  
  <%= @todo.project_name %>
</p>

<p>
  <strong>Project Description:</strong>
  <%= @todo.project_description %>
</p>

<p>
<strong>Mapping File:</strong>
<%= @todo.mapping_file %>
</p>
<p>
<strong>Mapping File:</strong>

<%= link_to 'Download Verbatim', todos_download_verbatim_url %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'View list', todos_path %></li>
  <li><%= link_to 'New Project', new_todo_path %></li>
</ul>

<table class="table">
  <thead>
 
    <tr>
      <th>Project Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td>
          <span class="has-tooltip" data-toggle="tooltip" title="<%= "Created on #{todo.created_at.strftime("%m/%e/%Y at %w:%M %p")}, Last modified on #{todo.updated_at.strftime("%m/%e/%Y at %w:%M %p")}" %>">
            <%= todo.project_name %>
          </span>
        </td>
        <td>
          <% if todo.project_description? %>
            <!-- Button trigger modal -->
            <button class="btn btn-link" data-toggle="modal" data-target="#todo-<%= todo.id %>-notes">
              View notes
            </button>

            <!-- Modal -->
            <div class="modal fade" id="todo-<%= todo.id %>-notes" tabindex="-1" role="dialog" aria-labelledby="todo-<%= todo.id %>-label" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title" id="todo-<%= todo.id %>-label">Description</h4>
                  </div>
                  <div class="modal-body">
                   
                    <%= todo.mapping_file_name%>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
          <% end %>

          <% if todo.notes? %>
            <button type="button" class="btn btn-link has-popover" data-toggle="popover" title="Notes" data-content="<%= todo.notes %>">View notes (popover)</button>
          <% end %>
        </td>
        <td><%= link_to 'Download Verbatim', "/uploads/#{todo.mapping_file_name}/verbatim_#{todo.mapping_file_name}", class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Download Graphs', "/uploads/#{todo.mapping_file_name}/graphs_#{todo.mapping_file_name}", class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Download User Inputs', "/uploads/exports/#{todo.project_name.truncate(30)}_inputs.xlsx", class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo), class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Todo', new_todo_path, class: 'btn btn-success' %>-->
<%= link_to new_todo_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> New Project<% end %>

app/views/todos/new.html.erb
<script type="text/javascript">
$(document).ready(function(){    
    //Check if the current URL contains '#'
    if(document.URL.indexOf("#")==-1){
        // Set the URL to whatever it was plus "#".
        url = document.URL+"#";
        location = "#";

        //Reload the page
        location.reload(true);
    }
});
</script>

<h1>New Project</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<h2 id="notice"><%= notice %></h2>




<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>